"""fix location datatype

Revision ID: 87fa8dba71b5
Revises: 8975d868e20a
Create Date: 2026-02-25 13:58:39.873987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87fa8dba71b5'
down_revision: Union[str, Sequence[str], None] = '8975d868e20a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('ALTER TABLE farms ALTER COLUMN location_lat TYPE double precision USING location_lat::double precision')
    op.execute('ALTER TABLE farms ALTER COLUMN location_lng TYPE double precision USING location_lng::double precision')
    op.execute('ALTER TABLE shops ALTER COLUMN location_lat TYPE double precision USING location_lat::double precision')
    op.execute('ALTER TABLE shops ALTER COLUMN location_lng TYPE double precision USING location_lng::double precision')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shops', 'location_lng',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('shops', 'location_lat',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('farms', 'location_lng',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('farms', 'location_lat',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
