"""create price history table

Revision ID: 8975d868e20a
Revises: d2278d1f62b8
Create Date: 2026-02-25 13:54:23.022696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8975d868e20a'
down_revision: Union[str, Sequence[str], None] = 'd2278d1f62b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_crop_type'), 'price_history', ['crop_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_crop_type'), table_name='price_history')
    op.drop_table('price_history')
    # ### end Alembic commands ###
